/*
 * This file was automatically generated by EvoSuite
 * Wed Feb 26 13:53:59 GMT 2020
 */

package com.github.jsonldjava.core;

import org.junit.Test;
import static org.junit.Assert.*;
import com.github.jsonldjava.core.JsonLdConsts;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class JsonLdConsts_ESTest extends JsonLdConsts_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      JsonLdConsts jsonLdConsts0 = new JsonLdConsts();
  }
}
