/*
 * This file was automatically generated by EvoSuite
 * Wed Feb 26 13:54:46 GMT 2020
 */

package com.github.jsonldjava.utils;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.github.jsonldjava.utils.JarCacheResource;
import java.io.IOException;
import java.io.InputStream;
import java.net.URL;
import java.net.URLStreamHandler;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.evosuite.runtime.mock.java.net.MockURL;
import org.evosuite.runtime.testdata.EvoSuiteURL;
import org.evosuite.runtime.testdata.NetworkHandling;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class JarCacheResource_ESTest extends JarCacheResource_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      URL uRL0 = MockURL.getHttpExample();
      JarCacheResource jarCacheResource0 = new JarCacheResource(uRL0);
      EvoSuiteURL evoSuiteURL0 = new EvoSuiteURL("http://www.someFakeButWellFormedURL.org/fooExample");
      NetworkHandling.createRemoteTextFile(evoSuiteURL0, "id+8");
      jarCacheResource0.dispose();
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      URL uRL0 = MockURL.getHttpExample();
      JarCacheResource jarCacheResource0 = new JarCacheResource(uRL0);
      long long0 = jarCacheResource0.length();
      assertEquals((-1L), long0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      URL uRL0 = MockURL.getHttpExample();
      JarCacheResource jarCacheResource0 = new JarCacheResource(uRL0);
      EvoSuiteURL evoSuiteURL0 = new EvoSuiteURL("http://www.someFakeButWellFormedURL.org/fooExample");
      NetworkHandling.createRemoteTextFile(evoSuiteURL0, "id+8");
      InputStream inputStream0 = jarCacheResource0.getInputStream();
      assertNotNull(inputStream0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      URL uRL0 = MockURL.getFtpExample();
      JarCacheResource jarCacheResource0 = new JarCacheResource(uRL0);
      // Undeclared exception!
      try { 
        jarCacheResource0.getInputStream();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.github.jsonldjava.utils.JarCacheResource", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      URLStreamHandler uRLStreamHandler0 = mock(URLStreamHandler.class, new ViolatedAssumptionAnswer());
      URL uRL0 = MockURL.URL("com.github.jsonldjava.utils.JarCacheResource", "k?>L", (-1), "com.github.jsonldjava.utils.JarCacheResource", uRLStreamHandler0);
      JarCacheResource jarCacheResource0 = new JarCacheResource(uRL0);
      // Undeclared exception!
      try { 
        jarCacheResource0.dispose();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.github.jsonldjava.utils.JarCacheResource", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      URL uRL0 = MockURL.getHttpExample();
      JarCacheResource jarCacheResource0 = new JarCacheResource(uRL0);
      try { 
        jarCacheResource0.getInputStream();
        fail("Expecting exception: IOException");
      
      } catch(IOException e) {
         //
         // Could not find: www.someFakeButWellFormedURL.org
         //
         verifyException("org.evosuite.runtime.mock.java.net.EvoHttpURLConnection", e);
      }
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      URL uRL0 = MockURL.getHttpExample();
      JarCacheResource jarCacheResource0 = new JarCacheResource(uRL0);
      jarCacheResource0.dispose();
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      URL uRL0 = MockURL.getFileExample();
      JarCacheResource jarCacheResource0 = new JarCacheResource(uRL0);
      // Undeclared exception!
      try { 
        jarCacheResource0.length();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.github.jsonldjava.utils.JarCacheResource", e);
      }
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      JarCacheResource jarCacheResource0 = null;
      try {
        jarCacheResource0 = new JarCacheResource((URL) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.evosuite.runtime.mock.java.net.MockURL", e);
      }
  }
}
