/*
 * This file was automatically generated by EvoSuite
 * Wed Feb 26 13:55:31 GMT 2020
 */

package com.github.jsonldjava.impl;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.github.jsonldjava.core.RDFDataset;
import com.github.jsonldjava.impl.NQuadRDFParser;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class NQuadRDFParser_ESTest extends NQuadRDFParser_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      NQuadRDFParser nQuadRDFParser0 = new NQuadRDFParser();
      RDFDataset rDFDataset0 = nQuadRDFParser0.parse("");
      try { 
        nQuadRDFParser0.parse(rDFDataset0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // invalid input: java.lang.String@0000000003
         //
         verifyException("com.github.jsonldjava.impl.NQuadRDFParser", e);
      }
  }
}
