/*
 * This file was automatically generated by EvoSuite
 * Wed Feb 26 13:55:31 GMT 2020
 */

package com.github.jsonldjava.impl;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.github.jsonldjava.core.RDFDataset;
import com.github.jsonldjava.impl.NQuadTripleCallback;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class NQuadTripleCallback_ESTest extends NQuadTripleCallback_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      NQuadTripleCallback nQuadTripleCallback0 = new NQuadTripleCallback();
      // Undeclared exception!
      try { 
        nQuadTripleCallback0.call((RDFDataset) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.github.jsonldjava.core.RDFDatasetUtils", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      NQuadTripleCallback nQuadTripleCallback0 = new NQuadTripleCallback();
      RDFDataset rDFDataset0 = new RDFDataset();
      Object object0 = new Object();
      rDFDataset0.put("", object0);
      // Undeclared exception!
      try { 
        nQuadTripleCallback0.call(rDFDataset0);
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // java.lang.Object cannot be cast to java.util.List
         //
         verifyException("com.github.jsonldjava.core.RDFDataset", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      NQuadTripleCallback nQuadTripleCallback0 = new NQuadTripleCallback();
      RDFDataset rDFDataset0 = new RDFDataset();
      Object object0 = nQuadTripleCallback0.call(rDFDataset0);
      assertEquals("", object0);
  }
}
